# Generated by Django 5.2.6 on 2025-09-25 01:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_menu_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookingDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
